name: CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  test_and_build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: sätta upp Java miljö
        uses: actions/setup-java@v5
        with:
          java-version: "17"
          distribution: "temurin"
          cache: "maven"

      - name: Bygga och köra tester
        run: mvn -B package


